import { ArrowUpRight, ArrowDown, Code2, Braces, GitPullRequest, Mail } from 'lucide-react';
const github = 'https://github.com/EstefaniaMancipeM';
const linkedin = 'https://www.linkedin.com/in/estefania-mancipe-76613648/';
const email = 'mailto:estefaniamancipe@gmail.com';
export default function Home() {
return <>
<a className="skip-link" href="#contenido">Saltar al contenido</a>
<header className="site-header"><a className="wordmark" href="#inicio" aria-label="Estefania Mancipe, inicio">em<span>.</span></a><nav aria-label="Navegación principal"><a href="#proyectos">Proyectos</a><a href="#sobre-mi">Sobre mí</a><a href="#habilidades">Habilidades</a></nav><a className="header-contact" href="#contacto">Hablemos <ArrowUpRight size={17}/></a></header>
<main id="contenido">
<section className="hero wrap" id="inicio" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> DESARROLLADORA FULL STACK JUNIOR</p><h1 id="hero-title">Estefania<br/><span>Mancipe.</span></h1><p className="hero-statement">Aprender a fondo.<br/>Construir con intención.</p><p className="hero-intro">Mi punto de partida es concreto: interfaces con JavaScript, lógica con Java y trabajo en equipo. Mi siguiente paso, conectar esas piezas.</p><a className="button primary" href="#proyectos">Explora mi trabajo <ArrowDown size={18}/></a><div className="hero-footnote"><span>01 — MI TRABAJO HABLA POR MÍ</span><span>HTML · CSS · JavaScript · Java</span></div></div><figure className="portrait"><img src="/estefania.webp" alt="Retrato de Estefania Mancipe Montañez" width="800" height="799" fetchPriority="high"/><figcaption><span>ESTEFANIA MANCIPE MONTAÑEZ</span><span>En formación. En movimiento.</span></figcaption></figure></section>
<section className="projects wrap section" id="proyectos" aria-labelledby="projects-title"><div className="section-heading"><p className="eyebrow">01 / PROYECTOS SELECCIONADOS</p><div><h2 id="projects-title">Tres formas de<br/><em>demostrar lo que hago.</em></h2><p>Un proyecto en equipo, una aplicación propia y un ejercicio de modelado. Cada uno exige pensar de una forma distinta.</p></div></div>
<article className="project featured"><div className="project-visual vidafit-visual"><span className="visual-label">PROYECTO COLABORATIVO / 01</span><img className="vidafit-logo" src="/vidafit-logo.png" alt="Logo original de VidaFit" width="818" height="301" loading="lazy"/><p>Un catálogo.<br/>Muchas decisiones.</p><div className="visual-tags"><span>Catálogo</span><span>Filtros</span><span>Contacto</span></div></div><div className="project-content"><p className="project-category">COMERCIO ELECTRÓNICO · EN DESARROLLO</p><h3>VidaFit</h3><p>Explorar suplementos y accesorios requiere poder comparar y encontrar lo relevante. VidaFit reúne catálogo, filtros, vistas de productos y carrito en una interfaz web.</p><dl><dt>Mi aporte</dt><dd>Trabajé en el catálogo y aporté ideas para el desarrollo del proyecto. Mi entrega de catálogo, imágenes y estilos de contacto quedó integrada mediante la pull request #9.</dd><dt>Un reto del proyecto</dt><dd>Combinar categoría, marca, precio y disponibilidad sin perder coherencia entre productos visibles y contador. El código separa el filtrado del ordenamiento para actualizar el catálogo.</dd><dt>Estado actual</dt><dd>Frontend y esquema SQL disponibles. La conexión con un backend sigue pendiente.</dd></dl><ul className="tags" aria-label="Tecnologías de VidaFit"><li>HTML</li><li>CSS</li><li>JavaScript</li><li>Bootstrap</li><li>Git</li></ul><div className="project-links"><a href="https://francosg2003.github.io/GenerartionsCo13_VidaFit/" target="_blank" rel="noreferrer">Ver demo <ArrowUpRight size={17}/></a><a href="https://github.com/FrancoSG2003/GenerartionsCo13_VidaFit" target="_blank" rel="noreferrer">Código <Code2 size={17}/></a><a href="https://github.com/FrancoSG2003/GenerartionsCo13_VidaFit/pull/9" target="_blank" rel="noreferrer">Mi contribución <GitPullRequest size={17}/></a></div></div></article>
<div className="project-pair"><article className="project"><div className="project-visual planner-visual"><span className="visual-label">APLICACIÓN INDIVIDUAL / 02</span><img className="project-diagram" src="/flujo-tareas.svg" alt="Flujo de Mis pendientes: crear, gestionar y guardar tareas" width="520" height="160" loading="lazy"/><p>Mis pendientes<span>JavaScript + almacenamiento local</span></p></div><div className="project-content"><p className="project-category">LÓGICA EN EL NAVEGADOR</p><h3>Mis pendientes</h3><p>Una agenda para registrar tareas con nombre, descripción y fecha, marcarlas como terminadas y eliminarlas de la lista.</p><dl><dt>Cómo está construido</dt><dd>La clase TaskManager organiza las tareas y separa su gestión de los eventos del formulario. La aplicación valida campos y guarda la colección en localStorage.</dd><dt>Qué demuestra</dt><dd>Manejo del DOM, objetos, identificadores y eventos delegados. El historial muestra la evolución desde tarjetas estáticas hasta una lista gestionada con JavaScript.</dd></dl><ul className="tags" aria-label="Tecnologías de Mis pendientes"><li>JavaScript</li><li>HTML / CSS</li><li>Bootstrap</li></ul><div className="project-links"><a href={`${github}/planificador-tareas`} target="_blank" rel="noreferrer">Explorar código <Code2 size={17}/></a><span className="pending">Demo actual pendiente</span></div></div></article>
<article className="project"><div className="project-visual java-visual"><span className="visual-label">MODELADO CON JAVA / 03</span><img className="project-diagram" src="/modelo-java.svg" alt="Modelo Java: clase Animal y especializaciones Perro, Gato, Ave y Conejo" width="520" height="160" loading="lazy"/><p>Clínica veterinaria<span>Un modelo común. Comportamientos distintos.</span></p></div><div className="project-content"><p className="project-category">PROGRAMACIÓN ORIENTADA A OBJETOS</p><h3>Clínica veterinaria</h3><p>Un ejercicio de consola que representa distintas especies, calcula sus consultas y organiza comportamientos de vacunación y seguro.</p><dl><dt>Cómo está construido</dt><dd>El modelo parte de Animal, una clase abstracta, y utiliza especializaciones e interfaces como Vacunable y Asegurable para expresar responsabilidades distintas.</dd><dt>Qué demuestra</dt><dd>Abstracción, herencia, interfaces y polimorfismo con Java. Es un ejercicio de fundamentos, sin API ni base de datos conectada.</dd></dl><ul className="tags" aria-label="Tecnologías de Clínica veterinaria"><li>Java</li><li>POO</li><li>Interfaces</li></ul><div className="project-links"><a href={`${github}/Sistema-de-Clinica-Veterinaria`} target="_blank" rel="noreferrer">Explorar código <Code2 size={17}/></a><span className="pending">Aplicación de consola</span></div></div></article></div></section>
<section className="about-section" id="sobre-mi" aria-labelledby="about-title"><div className="wrap about-grid"><p className="eyebrow">02 / SOBRE MÍ</p><div><h2 id="about-title">Me tomo en serio<br/><em>estar empezando.</em></h2><p className="about-lead">Quiero comprender lo que construyo, poder explicarlo y tener el criterio para mejorarlo.</p><p>Soy Estefania Mancipe Montañez y estoy formándome en desarrollo Full Stack Java. En mis proyectos conviven dos ejercicios: dar forma a una interfaz que alguien pueda usar y organizar la lógica que la hace funcionar.</p><p>En VidaFit aporto al catálogo y a las ideas del equipo. En mis ejercicios con Java exploro cómo repartir responsabilidades entre clases. Quiero avanzar con esa misma disposición: proponer, escuchar y corregir cuando una solución necesita otra mirada.</p><div className="about-note"><span>MI SIGUIENTE PASO</span><p>Conectar mis bases de frontend y Java en una aplicación completa.</p><ArrowUpRight aria-hidden="true"/></div></div></div></section>
<section className="wrap section" id="habilidades" aria-labelledby="skills-title"><div className="section-heading"><p className="eyebrow">03 / HABILIDADES</p><div><h2 id="skills-title">Las herramientas.<br/><em>Y lo que hago con ellas.</em></h2></div></div><div className="skills-grid"><article><Code2/><h3>Lenguajes</h3><p className="skills-names">JavaScript · Java<br/>HTML · CSS</p><p>Eventos y datos en el navegador, modelado con objetos y estructura de interfaces.</p></article><article><Braces/><h3>Interfaz</h3><p className="skills-names">Bootstrap 5<br/>DOM · localStorage</p><p>Maquetación, validación de formularios y persistencia local de tareas.</p></article><article><GitPullRequest/><h3>Trabajo compartido</h3><p className="skills-names">Git · GitHub</p><p>Versiones de mi trabajo y contribuciones que se integran mediante pull requests.</p></article></div><p className="learning-note">En desarrollo: mi camino hacia la integración de frontend, backend y bases de datos.</p></section>
<section className="contact-section" id="contacto" aria-labelledby="contact-title"><div className="wrap"><p className="eyebrow">04 / CONTACTO</p><div className="contact-row"><h2 id="contact-title">Tengo mucho<br/>por construir<span>.</span></h2><div><p>Busco mi primera oportunidad como desarrolladora Full Stack Junior. Conversemos sobre el trabajo y lo que puedo aportar.</p><a className="button primary" href={email}>Escríbeme <Mail size={20}/></a><a className="email-text" href={email}>estefaniamancipe@gmail.com</a></div></div></div></section>
</main><footer className="wrap site-footer"><a className="wordmark" href="#inicio">em<span>.</span></a><p>Estefania Mancipe Montañez · 2026</p><div><a href={github} target="_blank" rel="noreferrer"><Code2 size={17}/> GitHub</a><a href={linkedin} target="_blank" rel="noreferrer"><ArrowUpRight size={17}/> LinkedIn</a></div></footer>
</>;
}


